# Generated by Django 6.1.1 on 2026-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_twits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='profile/cover_images'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile/images'),
        ),
    ]
